server:
  port: 2003

spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 使用服务发现客户端接口DiscoveryClient，从服务注册中心获取服务注册信息，然后配置相应的路由。
          enabled: true
          # 将请求路径上的服务名配置为小写
          lower-case-service-id: true
      routes:
        # id：我们自定义的路由 ID，保持唯一
        - id: demo-business-test
          # uri：目标服务地址
          uri: lb://demo-business
          # predicates：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
          predicates:
            - Path=/business/**

ribbon:
  # 设置Ribbon的饥饿加载(eager-load)模式。
  # http建立socket超时时间,毫秒
  ConnectTimeout: 5000
  # http读取响应socket超时时间
  ReadTimeout: 8000
#  eager-load:
#    enabled: true # 开启Ribbon的饥饿加载模式
#    clients: ts-auth,ts-biz-support # 指定需要饥饿加载的服务名